AllCops:
  Exclude:
    - Gemfile
    - db/**
    - db/migrate/**
    - bin/**
    - config/**
    - config/initializers/**
Rails:
  Enabled: true

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/DynamicFindBy:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Rails/Date:
  Enabled: false

Rails/FilePath:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
   Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/DateTime:
   Enabled: false

Metrics/CyclomaticComplexity:
   Enabled: false

Metrics/PerceivedComplexity:
   Enabled: false

Style/ClassAndModuleChildren:
   Enabled: false

Metrics/ModuleLength:
   Enabled: false

Lint/AmbiguousBlockAssociation:
   Enabled: false

Style/ConditionalAssignment:
   Enabled: false

Style/Documentation:
   Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
