default: &default
  adapter: postgresql
  encoding: unicode
  host: trello_db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: trello_development


test:
  <<: *default
  database: trello_test
